// 合成測試資料，僅用於驗證 schema / 計分邏輯，不是真實考題內容
export const sampleQuestions = [
  {
    exam: "gsat",
    year: 111,
    subject: "mathB",
    questionNumber: 1,
    groupId: "1",
    type: "single",
    stem: "（測試用單選題）下列何者為真？",
    options: { A: "選項A", B: "選項B", C: "選項C", D: "選項D" },
    correctAnswer: "B",
    score: 5,
  },
  {
    exam: "gsat",
    year: 111,
    subject: "mathB",
    questionNumber: 8,
    groupId: "8",
    type: "multiple",
    stem: "（測試用多選題）下列哪些選項正確？",
    options: { A: "a", B: "b", C: "c", D: "d", E: "e" },
    correctAnswer: ["A", "C", "D"],
    optionCount: 5,
    score: 2,
  },
  {
    exam: "gsat",
    year: 111,
    subject: "mathB",
    questionNumber: 13,
    groupId: "13",
    type: "fill",
    stem: "（測試用選填題）化簡後的分數是？",
    blanks: ["13-1", "13-2"],
    correctAnswer: ["3", "8"],
    score: 5,
  },
  // 混合題組：18單選（計分）+ 19、20非選擇題（不計分，僅供對答案）
  {
    exam: "gsat",
    year: 111,
    subject: "mathB",
    questionNumber: 18,
    groupId: "18-20",
    type: "single",
    stem: "某函數如圖所示。第18題：下列敘述正確的是？",
    options: { A: "選項A", B: "選項B", C: "選項C" },
    correctAnswer: "A",
    score: 5,
  },
  {
    exam: "gsat",
    year: 111,
    subject: "mathB",
    questionNumber: 19,
    groupId: "18-20",
    type: "essay",
    stem: "某函數如圖所示。第19題：請說明你的計算過程。",
    referenceAnswer: "（測試用參考詳解：計算過程說明……）",
    score: 4,
  },
  {
    exam: "gsat",
    year: 111,
    subject: "mathB",
    questionNumber: 20,
    groupId: "18-20",
    type: "essay",
    stem: "某函數如圖所示。第20題：請求出最終答案並說明理由。",
    referenceAnswer: "（測試用參考詳解：最終答案與理由……）",
    score: 6,
  },
];

export const sampleMeta = {
  exam: "gsat",
  year: 111,
  subject: "mathB",
  subjectLabel: "數學B",
  examLabel: "大學學科能力測驗",
};
